name: 'CodeQL: Init'
description: 'Setup the CodeQL tracer'
author: 'GitHub'
inputs:
  tools:
    description: URL of CodeQL tools
    required: false
    default: https://github.com/github/codeql-action/releases/download/codeql-bundle-20200630/codeql-bundle.tar.gz
  languages:
    description: The languages to be analysed
    required: false
  token:
    default: ${{ github.token }}
  matrix:
    default: ${{ toJson(matrix) }}
  github:
    default: ${{ toJson(github) }}
  config-file:
    description: Path of the config file to use
    required: false
runs:
  using: 'node12'
  main: '../lib/setup-tracer.js'
